<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Nncase</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TargetFramework>net9.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nncase.Core\Nncase.Core.csproj" />
  </ItemGroup>

</Project>
