<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Nncase</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
	<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <TargetFramework>net9.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrtKISharp" />
    <PackageReference Include="System.Linq.Async" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\Nncase.Core\Nncase.Core.csproj" />
    <ProjectReference Include="..\Nncase.Passes\Nncase.Passes.csproj" />
  </ItemGroup>

</Project>
