<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Nncase</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TargetFramework>net9.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Extension.Mathematics" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nncase.Core\Nncase.Core.csproj" />
    <ProjectReference Include="..\Nncase.IO\Nncase.IO.csproj" />
  </ItemGroup>

</Project>
